---
title: '`alluseful`: my personal R package'
author: Josh Moatt 
date: today
date-format: "DD/MM/YYYY"
format:
  gfm: default
toc: true
editor_options:
  chunk_output_type: console
---

## 📖 Overview

`alluseful` is my personal package housing useful functions and addins, as well as custom themes for RStudio and font installs. Most of these features have been developed to simplify and standardise my ways of working. Some of the functions here have been developed for wider use and are included in the package [fssetup](https://github.com/Defra-Data-Science-Centre-of-Excellence/fssetup).

> \[!WARNING\] \* This package is intend for my own use and none of the functions or features have been tested for widespread use. \> \* As this was not intended for widespread use, the code underlying this functions is not pretty.

## 🗝️ Key features

-   Functions for automating the set up of the RStudio IDE - preferences, pane layout etc
-   Custom console prompt showing a farming themed emoji and active git branch
-   Project template - so all new RStudio projects are pre-populated with key files
-   Script template - so all new scripts open with a standardised header including key meta-data
-   Various additional templates - README, .gitignore etc
-   Various functions for integrating RStudio with GitHub - connecting via PAT and SSH, creating repos etc
-   Five custom themes - versions of existing RStudio themes modified to suit my preferences
-   Various open source editor fonts
-   Various addins and shortcuts
